version: 0.2

phases:
  install:
    commands:
    # Install Node 12
    - apt-get update
    - apt-get install -y apt-transport-https
    - apt-get install -y nodejs
    # Install Yarn
    - npm install -g yarn
  pre_build:
    commands:
    # Install dependencies
    - yarn
  build:
    commands:
    # tests
    # build
    - yarn build 

